### ISSUE TITLE
Can I use Owin hosting to IIS instead of Self Hosting or Windows Service 

### ISSUE THREAD

**Issue by ShashikantMaurya** [rbanks54/microcafe#13]
Hi,

I have used owin hosting to IIS, it is taking too long to appendStream(i.e. eventStoreConnection.AppendToStreamAsync) into EventStore.Please help me asap

**Comment by rbanks54** [comment]
Performance issues with EventStore should be directed to the https://github.com/EventStore/EventStore project.
